name: Quote API Requests

on:
  push:
    branches:
      - main

jobs:
  random_quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start the application
        run: |
          nohup uvicorn main:app --reload &  # Запускаем сервер в фоновом режиме

      - name: Wait for the server to start
        run: sleep 5  # Даем время серверу на запуск

      - name: Get Random Quote
        run: |
          curl -X GET "http://127.0.0.1:8000/random_quote" -H "Accept: application/json"

  add_quote_valid_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start the application
        run: |
          nohup uvicorn main:app --reload &  # Запускаем сервер в фоновом режиме

      - name: Wait for the server to start
        run: sleep 5  # Даем время серверу на запуск

      - name: Add Quote with Valid Token
        run: |
          curl -X POST "http://127.0.0.1:8000/add_quote" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "x-token: your_secret_token" \
          -d '{"text": "Тестовая цитата для добавления.", "author": "Автор Теста", "theme": "Тест"}'

  add_quote_invalid_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start the application
        run: |
          nohup uvicorn main:app --reload &  # Запускаем сервер в фоновом режиме

      - name: Wait for the server to start
        run: sleep 5  # Даем время серверу на запуск

      - name: Add Quote with Invalid Token
        run: |
          curl -X POST "http://127.0.0.1:8000/add_quote" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "x-token: invalid_token" \
          -d '{"text": "Тестовая цитата с неправильным токеном.", "author": "Автор Теста", "theme": "Тест"}'

  update_quote_valid_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start the application
        run: |
          nohup uvicorn main:app --reload &  # Запускаем сервер в фоновом режиме

      - name: Wait for the server to start
        run: sleep 5  # Даем время серверу на запуск

      - name: Update Quote with Valid Token
        run: |
          curl -X PUT "http://127.0.0.1:8000/update_quote/1" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "x-token: your_secret_token" \
          -d '{"text": "Обновленная тестовая цитата.", "author": "Обновленный Автор", "theme": "Обновленный Тест"}'

  update_quote_invalid_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start the application
        run: |
          nohup uvicorn main:app --reload &  # Запускаем сервер в фоновом режиме

      - name: Wait for the server to start
        run: sleep 5  # Даем время серверу на запуск

      - name: Update Quote with Invalid Token
        run: |
          curl -X PUT "http://127.0.0.1:8000/update_quote/1" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "x-token: invalid_token" \
          -d '{"text": "Тестовая цитата с неправильным токеном для обновления.", "author": "Автор Теста", "theme": "Тест"}'

  delete_quote_valid_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start the application
        run: |
          nohup uvicorn main:app --reload &  # Запускаем сервер в фоновом режиме

      - name: Wait for the server to start
        run: sleep 5  # Даем время серверу на запуск

      - name: Delete Quote with Valid Token
        run: |
          curl -X DELETE "http://127.0.0.1:8000/delete_quote/1" \
          -H "Accept: application/json" \
          -H "x-token: your_secret_token"

  delete_quote_invalid_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start the application
        run: |
          nohup uvicorn main:app --reload &  # Запускаем сервер в фоновом режиме

      - name: Wait for the server to start
        run: sleep 5  # Даем время серверу на запуск

      - name: Delete Quote with Invalid Token
        run: |
          curl -X DELETE "http://127.0.0.1:8000/delete_quote/1" \
          -H "Accept: application/json" \
          -H "x-token: invalid_token"
